networks:
  dev:

services:
  backend:
    build:
      context: ./backend
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=1123
      - DB_NAME=IT911
      - SECRET_KEY=4f2a8e9d9d41d87f1e8d93c1f88c95e3a582ebceac89dfc3a4582ff31c60c0b3
      - ACCESS_TIME=2
      - REFRESH_TIME=3
    networks:
      - dev
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    networks:
      - dev
    restart: unless-stopped
