networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - backend
      - frontend
    networks:
      - dev
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - ACCESS_TIME=${ACCESS_TIME}
      - REFRESH_TIME=${REFRESH_TIME}
    networks:
      - dev
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    networks:
      - dev
    restart: unless-stopped
